# TCL File Generated by Component Editor 14.1
# Sat May 02 10:35:54 CST 2015
# DO NOT MODIFY


# 
# avalon_shell_rsa "avalon_shell_rsa" v1.0
#  2015.05.02.10:35:54
# 
# 

# 
# request TCL package from ACDS 14.1
# 
package require -exact qsys 14.1


# 
# module avalon_shell_rsa
# 
set_module_property DESCRIPTION ""
set_module_property NAME avalon_shell_rsa
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP custom_logic
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME avalon_shell_rsa
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_shell_rsa
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_shell_rsa.v VERILOG PATH avalon_shell_rsa.v TOP_LEVEL_FILE
add_fileset_file avalon_shell_rsa.sdc SDC PATH avalon_shell_rsa.sdc


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point m0
# 
add_interface m0 avalon start
set_interface_property m0 addressUnits SYMBOLS
set_interface_property m0 associatedClock clock
set_interface_property m0 associatedReset reset
set_interface_property m0 bitsPerSymbol 8
set_interface_property m0 burstOnBurstBoundariesOnly false
set_interface_property m0 burstcountUnits WORDS
set_interface_property m0 doStreamReads false
set_interface_property m0 doStreamWrites false
set_interface_property m0 holdTime 0
set_interface_property m0 linewrapBursts false
set_interface_property m0 maximumPendingReadTransactions 0
set_interface_property m0 maximumPendingWriteTransactions 0
set_interface_property m0 readLatency 0
set_interface_property m0 readWaitTime 1
set_interface_property m0 setupTime 0
set_interface_property m0 timingUnits Cycles
set_interface_property m0 writeWaitTime 0
set_interface_property m0 ENABLED true
set_interface_property m0 EXPORT_OF ""
set_interface_property m0 PORT_NAME_MAP ""
set_interface_property m0 CMSIS_SVD_VARIABLES ""
set_interface_property m0 SVD_ADDRESS_GROUP ""

add_interface_port m0 avm_m0_waitrequest waitrequest Input 1
add_interface_port m0 avm_m0_address address Output 32
add_interface_port m0 avm_m0_read read Output 1
add_interface_port m0 avm_m0_write write Output 1
add_interface_port m0 avm_m0_readdata readdata Input 8
add_interface_port m0 avm_m0_writedata writedata Output 8


# 
# connection point desgin_waitrequest
# 
add_interface desgin_waitrequest conduit end
set_interface_property desgin_waitrequest associatedClock clock
set_interface_property desgin_waitrequest associatedReset ""
set_interface_property desgin_waitrequest ENABLED true
set_interface_property desgin_waitrequest EXPORT_OF ""
set_interface_property desgin_waitrequest PORT_NAME_MAP ""
set_interface_property desgin_waitrequest CMSIS_SVD_VARIABLES ""
set_interface_property desgin_waitrequest SVD_ADDRESS_GROUP ""

add_interface_port desgin_waitrequest avm_design_waitrequest desgin_waitrequest Output 1


# 
# connection point design_address
# 
add_interface design_address conduit end
set_interface_property design_address associatedClock clock
set_interface_property design_address associatedReset ""
set_interface_property design_address ENABLED true
set_interface_property design_address EXPORT_OF ""
set_interface_property design_address PORT_NAME_MAP ""
set_interface_property design_address CMSIS_SVD_VARIABLES ""
set_interface_property design_address SVD_ADDRESS_GROUP ""

add_interface_port design_address avm_design_address design_address Input 32


# 
# connection point design_read
# 
add_interface design_read conduit end
set_interface_property design_read associatedClock clock
set_interface_property design_read associatedReset ""
set_interface_property design_read ENABLED true
set_interface_property design_read EXPORT_OF ""
set_interface_property design_read PORT_NAME_MAP ""
set_interface_property design_read CMSIS_SVD_VARIABLES ""
set_interface_property design_read SVD_ADDRESS_GROUP ""

add_interface_port design_read avm_design_read design_read Input 1


# 
# connection point design_write
# 
add_interface design_write conduit end
set_interface_property design_write associatedClock clock
set_interface_property design_write associatedReset ""
set_interface_property design_write ENABLED true
set_interface_property design_write EXPORT_OF ""
set_interface_property design_write PORT_NAME_MAP ""
set_interface_property design_write CMSIS_SVD_VARIABLES ""
set_interface_property design_write SVD_ADDRESS_GROUP ""

add_interface_port design_write avm_design_write design_write Input 1


# 
# connection point design_readdata
# 
add_interface design_readdata conduit end
set_interface_property design_readdata associatedClock ""
set_interface_property design_readdata associatedReset ""
set_interface_property design_readdata ENABLED true
set_interface_property design_readdata EXPORT_OF ""
set_interface_property design_readdata PORT_NAME_MAP ""
set_interface_property design_readdata CMSIS_SVD_VARIABLES ""
set_interface_property design_readdata SVD_ADDRESS_GROUP ""

add_interface_port design_readdata avm_design_readdata design_readdata Output 8


# 
# connection point design_writedata
# 
add_interface design_writedata conduit end
set_interface_property design_writedata associatedClock clock
set_interface_property design_writedata associatedReset ""
set_interface_property design_writedata ENABLED true
set_interface_property design_writedata EXPORT_OF ""
set_interface_property design_writedata PORT_NAME_MAP ""
set_interface_property design_writedata CMSIS_SVD_VARIABLES ""
set_interface_property design_writedata SVD_ADDRESS_GROUP ""

add_interface_port design_writedata avm_design_writedata design_writedata Input 8

